// Mocks generated by Mockito 5.4.4 from annotations
// in re_view/test/core/thumbnail_cache_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pdfx/src/renderer/interfaces/page.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PdfPageImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfPageImage extends _i1.Mock implements _i2.PdfPageImage {
  @override
  int get pageNumber =>
      (super.noSuchMethod(
            Invocation.getter(#pageNumber),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.Uint8List get bytes =>
      (super.noSuchMethod(
            Invocation.getter(#bytes),
            returnValue: _i3.Uint8List(0),
            returnValueForMissingStub: _i3.Uint8List(0),
          )
          as _i3.Uint8List);

  @override
  _i2.PdfPageImageFormat get format =>
      (super.noSuchMethod(
            Invocation.getter(#format),
            returnValue: _i2.PdfPageImageFormat.jpeg,
            returnValueForMissingStub: _i2.PdfPageImageFormat.jpeg,
          )
          as _i2.PdfPageImageFormat);

  @override
  int get quality =>
      (super.noSuchMethod(
            Invocation.getter(#quality),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}
