// Mocks generated by Mockito 5.4.4 from annotations
// in re_view/test/shared/widgets_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:re_view/core/lecture_loading_service.dart' as _i5;
import 'package:re_view/data/hive_models.dart' as _i2;

import 'widgets_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHiveTag_0 extends _i1.SmartFake implements _i2.HiveTag {
  _FakeHiveTag_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CallbackHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallbackHandler extends _i1.Mock implements _i3.CallbackHandler {
  MockCallbackHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call() => super.noSuchMethod(
    Invocation.method(#call, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BoolCallbackHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoolCallbackHandler extends _i1.Mock
    implements _i3.BoolCallbackHandler {
  MockBoolCallbackHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(bool? value) => super.noSuchMethod(
    Invocation.method(#call, [value]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HiveTag].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveTag extends _i1.Mock implements _i2.HiveTag {
  MockHiveTag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  set id(String? _id) => super.noSuchMethod(
    Invocation.setter(#id, _id),
    returnValueForMissingStub: null,
  );

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  set name(String? _name) => super.noSuchMethod(
    Invocation.setter(#name, _name),
    returnValueForMissingStub: null,
  );

  @override
  int get color =>
      (super.noSuchMethod(Invocation.getter(#color), returnValue: 0) as int);

  @override
  set color(int? _color) => super.noSuchMethod(
    Invocation.setter(#color, _color),
    returnValueForMissingStub: null,
  );

  @override
  _i2.HiveTag copyWith({String? id, String? name, int? color}) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #name: name,
              #color: color,
            }),
            returnValue: _FakeHiveTag_0(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #name: name,
                #color: color,
              }),
            ),
          )
          as _i2.HiveTag);
}

/// A class which mocks [LectureLoadingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLectureLoadingService extends _i1.Mock
    implements _i5.LectureLoadingService {
  MockLectureLoadingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  double get progress =>
      (super.noSuchMethod(Invocation.getter(#progress), returnValue: 0.0)
          as double);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  String get lectureTitle =>
      (super.noSuchMethod(
            Invocation.getter(#lectureTitle),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#lectureTitle),
            ),
          )
          as String);

  @override
  bool get isCancelled =>
      (super.noSuchMethod(Invocation.getter(#isCancelled), returnValue: false)
          as bool);

  @override
  bool get isCollapsed =>
      (super.noSuchMethod(Invocation.getter(#isCollapsed), returnValue: false)
          as bool);

  @override
  bool get bubbleOnRight =>
      (super.noSuchMethod(Invocation.getter(#bubbleOnRight), returnValue: false)
          as bool);

  @override
  double get bubbleX =>
      (super.noSuchMethod(Invocation.getter(#bubbleX), returnValue: 0.0)
          as double);

  @override
  double get bubbleY =>
      (super.noSuchMethod(Invocation.getter(#bubbleY), returnValue: 0.0)
          as double);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  String get errorTitle =>
      (super.noSuchMethod(
            Invocation.getter(#errorTitle),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#errorTitle),
            ),
          )
          as String);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setOnCancel(_i6.VoidCallback? callback) => super.noSuchMethod(
    Invocation.method(#setOnCancel, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void startLoading(String? title, int? audioCount) => super.noSuchMethod(
    Invocation.method(#startLoading, [title, audioCount]),
    returnValueForMissingStub: null,
  );

  @override
  double getProgress() =>
      (super.noSuchMethod(Invocation.method(#getProgress, []), returnValue: 0.0)
          as double);

  @override
  double computeProgress() =>
      (super.noSuchMethod(
            Invocation.method(#computeProgress, []),
            returnValue: 0.0,
          )
          as double);

  @override
  void updateProgress(double? progress, int? order, String? message) =>
      super.noSuchMethod(
        Invocation.method(#updateProgress, [progress, order, message]),
        returnValueForMissingStub: null,
      );

  @override
  void completeLoading({String? lectureId}) => super.noSuchMethod(
    Invocation.method(#completeLoading, [], {#lectureId: lectureId}),
    returnValueForMissingStub: null,
  );

  @override
  void hideLoading() => super.noSuchMethod(
    Invocation.method(#hideLoading, []),
    returnValueForMissingStub: null,
  );

  @override
  void setError({String? errorTitle, String? errorMessage}) =>
      super.noSuchMethod(
        Invocation.method(#setError, [], {
          #errorTitle: errorTitle,
          #errorMessage: errorMessage,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void cancelLoading() => super.noSuchMethod(
    Invocation.method(#cancelLoading, []),
    returnValueForMissingStub: null,
  );

  @override
  void collapseToBubble({required bool? alignRight}) => super.noSuchMethod(
    Invocation.method(#collapseToBubble, [], {#alignRight: alignRight}),
    returnValueForMissingStub: null,
  );

  @override
  void expandFromBubble() => super.noSuchMethod(
    Invocation.method(#expandFromBubble, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateBubblePosition(double? x, double? y) => super.noSuchMethod(
    Invocation.method(#updateBubblePosition, [x, y]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
