// Mocks generated by Mockito 5.4.4 from annotations
// in re_view/test/features/player/player_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:just_audio/just_audio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pdfx/pdfx.dart' as _i6;
import 'package:re_view/features/player/services/audio_service.dart' as _i2;
import 'package:re_view/features/player/services/pdf_cache_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i2.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i3.Stream<Duration>.empty(),
      ) as _i3.Stream<Duration>);

  @override
  _i3.Stream<_i4.PlayerState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i3.Stream<_i4.PlayerState>.empty(),
      ) as _i3.Stream<_i4.PlayerState>);

  @override
  _i3.Future<void> loadAudio(String? path) => (super.noSuchMethod(
        Invocation.method(
          #loadAudio,
          [path],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [PdfCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfCacheService extends _i1.Mock implements _i5.PdfCacheService {
  MockPdfCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setPdfDocument(_i6.PdfDocument? document) => super.noSuchMethod(
        Invocation.method(
          #setPdfDocument,
          [document],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cacheSinglePage(int? pageNumber) => super.noSuchMethod(
        Invocation.method(
          #cacheSinglePage,
          [pageNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i7.Uint8List> getCachedOrRenderPage(int? pageNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedOrRenderPage,
          [pageNumber],
        ),
        returnValue: _i3.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i3.Future<_i7.Uint8List>);

  @override
  _i7.Uint8List? getCachedImageDirect(int? pageNumber) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedImageDirect,
        [pageNumber],
      )) as _i7.Uint8List?);

  @override
  void setCachedImage(
    int? pageNumber,
    _i7.Uint8List? imageBytes,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setCachedImage,
          [
            pageNumber,
            imageBytes,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getLoadingCount() => (super.noSuchMethod(
        Invocation.method(
          #getLoadingCount,
          [],
        ),
        returnValue: 0,
      ) as int);
}
