// Mocks generated by Mockito 5.4.4 from annotations
// in re_view/test/features/player/player_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i12;

import 'package:hive_flutter/hive_flutter.dart' as _i11;
import 'package:just_audio/just_audio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:pdfx/pdfx.dart' as _i2;
import 'package:re_view/data/hive_manager.dart' as _i10;
import 'package:re_view/data/hive_models.dart' as _i3;
import 'package:re_view/features/player/core/pdf_cache_service.dart' as _i7;
import 'package:re_view/features/player/services/audio_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePdfPage_0 extends _i1.SmartFake implements _i2.PdfPage {
  _FakePdfPage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppSettings_1 extends _i1.SmartFake implements _i3.AppSettings {
  _FakeAppSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUiState_2 extends _i1.SmartFake implements _i3.UiState {
  _FakeUiState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i4.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i5.Stream<Duration>.empty(),
      ) as _i5.Stream<Duration>);

  @override
  _i5.Stream<_i6.PlayerState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i5.Stream<_i6.PlayerState>.empty(),
      ) as _i5.Stream<_i6.PlayerState>);

  @override
  _i5.Future<void> loadAudio(String? path) => (super.noSuchMethod(
        Invocation.method(
          #loadAudio,
          [path],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [PdfCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfCacheService extends _i1.Mock implements _i7.PdfCacheService {
  MockPdfCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setPdfDocument(_i2.PdfDocument? document) => super.noSuchMethod(
        Invocation.method(
          #setPdfDocument,
          [document],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cacheSinglePage(int? pageNumber) => super.noSuchMethod(
        Invocation.method(
          #cacheSinglePage,
          [pageNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i8.Uint8List> getCachedOrRenderPage(int? pageNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedOrRenderPage,
          [pageNumber],
        ),
        returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i5.Future<_i8.Uint8List>);

  @override
  _i8.Uint8List? getCachedImageDirect(int? pageNumber) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedImageDirect,
        [pageNumber],
      )) as _i8.Uint8List?);

  @override
  void setCachedImage(
    int? pageNumber,
    _i8.Uint8List? imageBytes,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setCachedImage,
          [
            pageNumber,
            imageBytes,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getLoadingCount() => (super.noSuchMethod(
        Invocation.method(
          #getLoadingCount,
          [],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [PdfDocument].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfDocument extends _i1.Mock implements _i2.PdfDocument {
  MockPdfDocument() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get sourceName => (super.noSuchMethod(
        Invocation.getter(#sourceName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#sourceName),
        ),
      ) as String);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  int get pagesCount => (super.noSuchMethod(
        Invocation.getter(#pagesCount),
        returnValue: 0,
      ) as int);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  set isClosed(bool? _isClosed) => super.noSuchMethod(
        Invocation.setter(
          #isClosed,
          _isClosed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.PdfPage> getPage(
    int? pageNumber, {
    bool? autoCloseAndroid = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPage,
          [pageNumber],
          {#autoCloseAndroid: autoCloseAndroid},
        ),
        returnValue: _i5.Future<_i2.PdfPage>.value(_FakePdfPage_0(
          this,
          Invocation.method(
            #getPage,
            [pageNumber],
            {#autoCloseAndroid: autoCloseAndroid},
          ),
        )),
      ) as _i5.Future<_i2.PdfPage>);
}

/// A class which mocks [HiveManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveManager extends _i1.Mock implements _i10.HiveManager {
  MockHiveManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.AppSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeAppSettings_1(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i3.AppSettings);

  @override
  Map<String, _i3.HiveSubject> get subjects => (super.noSuchMethod(
        Invocation.getter(#subjects),
        returnValue: <String, _i3.HiveSubject>{},
      ) as Map<String, _i3.HiveSubject>);

  @override
  Map<String, _i3.HiveTag> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <String, _i3.HiveTag>{},
      ) as Map<String, _i3.HiveTag>);

  @override
  _i3.UiState get uiState => (super.noSuchMethod(
        Invocation.getter(#uiState),
        returnValue: _FakeUiState_2(
          this,
          Invocation.getter(#uiState),
        ),
      ) as _i3.UiState);

  @override
  Map<String, _i3.HiveLecture> get lectures => (super.noSuchMethod(
        Invocation.getter(#lectures),
        returnValue: <String, _i3.HiveLecture>{},
      ) as Map<String, _i3.HiveLecture>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initForTesting(_i11.Box<_i3.AppData>? box) =>
      (super.noSuchMethod(
        Invocation.method(
          #initForTesting,
          [box],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTheme(String? theme) => (super.noSuchMethod(
        Invocation.method(
          #updateTheme,
          [theme],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #updateLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAccessibility({
    bool? highContrast,
    bool? reduceMotion,
    bool? emphasizeCaptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccessibility,
          [],
          {
            #highContrast: highContrast,
            #reduceMotion: reduceMotion,
            #emphasizeCaptions: emphasizeCaptions,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTts({
    String? gender,
    String? speed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTts,
          [],
          {
            #gender: gender,
            #speed: speed,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTagColorTheme(String? theme) => (super.noSuchMethod(
        Invocation.method(
          #updateTagColorTheme,
          [theme],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i3.HiveSubject> getSubjects({
    bool? favoritesOnly = false,
    List<String>? filterTagIds = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubjects,
          [],
          {
            #favoritesOnly: favoritesOnly,
            #filterTagIds: filterTagIds,
          },
        ),
        returnValue: <_i3.HiveSubject>[],
      ) as List<_i3.HiveSubject>);

  @override
  _i3.HiveSubject? getSubject(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getSubject,
        [id],
      )) as _i3.HiveSubject?);

  @override
  _i5.Future<void> toggleSubjectFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleSubjectFavorite,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSubject(
    String? id, {
    String? title,
    bool? favorite,
    List<String>? tagIds,
    List<String>? lectureIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubject,
          [id],
          {
            #title: title,
            #favorite: favorite,
            #tagIds: tagIds,
            #lectureIds: lectureIds,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createSubject(
    String? title,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubject,
          [
            title,
            tagIds,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSubject(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSubject,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSubjectTitle(
    String? id,
    String? title,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubjectTitle,
          [
            id,
            title,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSubjectLectures(
    String? id,
    List<String>? lectureIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubjectLectures,
          [
            id,
            lectureIds,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSubjectTags(
    String? id,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubjectTags,
          [
            id,
            tagIds,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i3.HiveTag> getTags() => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [],
        ),
        returnValue: <_i3.HiveTag>[],
      ) as List<_i3.HiveTag>);

  @override
  _i5.Future<void> saveTags(List<_i3.HiveTag>? newTags) => (super.noSuchMethod(
        Invocation.method(
          #saveTags,
          [newTags],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool getSubjectExpandedState(String? subjectId) => (super.noSuchMethod(
        Invocation.method(
          #getSubjectExpandedState,
          [subjectId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setSubjectExpandedState(
    String? subjectId,
    bool? expanded,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubjectExpandedState,
          [
            subjectId,
            expanded,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> getRecentSearches() => (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<void> addRecentSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #addRecentSearch,
          [query],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRecentSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #removeRecentSearch,
          [query],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addLecture(_i3.HiveLecture? lecture) => (super.noSuchMethod(
        Invocation.method(
          #addLecture,
          [lecture],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.HiveLecture? getLecture(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getLecture,
        [id],
      )) as _i3.HiveLecture?);

  @override
  List<_i3.HiveLecture> getLecturesBySubject(String? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLecturesBySubject,
          [subjectId],
        ),
        returnValue: <_i3.HiveLecture>[],
      ) as List<_i3.HiveLecture>);

  @override
  List<_i3.HiveLecture> getLecturesByIds(List<String>? lectureIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLecturesByIds,
          [lectureIds],
        ),
        returnValue: <_i3.HiveLecture>[],
      ) as List<_i3.HiveLecture>);

  @override
  _i5.Future<void> updateLecture(_i3.HiveLecture? lecture) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLecture,
          [lecture],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLectureMetadata(
    String? id, {
    String? weekLabel,
    String? title,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLectureMetadata,
          [id],
          {
            #weekLabel: weekLabel,
            #title: title,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLecture(String? lectureId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLecture,
          [lectureId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i3.HiveLecture> searchLectures(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchLectures,
          [query],
        ),
        returnValue: <_i3.HiveLecture>[],
      ) as List<_i3.HiveLecture>);

  @override
  List<_i3.HiveLecture> getAllLectures({bool? newestFirst = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLectures,
          [],
          {#newestFirst: newestFirst},
        ),
        returnValue: <_i3.HiveLecture>[],
      ) as List<_i3.HiveLecture>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
