name: CI

on:
  push:
    branches: [ main, frontend ]
  pull_request:
    branches: [ main, frontend ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Add build requirements accordingly.
    #- name: Install Rust
    #  uses: actions-rs/toolchain@v1
    #  with:
    #   toolchain: stable
    #   override: true
    #   components: rustfmt, clippy

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Add necessary script executions accordingly.
    - name: Run lecture fetch unit tests
      run: flutter test test/features/edit/lecture_fetch_test.dart

    - name: Run player unit tests
      run: flutter test test/features/player/

    - name: Run search screen unit tests
      run: flutter test test/features/search/search_screen_test.dart

    - name: Run home screen unit tests
      run: flutter test test/features/home/

  # Linter for Dart: warnings are treated as errors
  dart-linter-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
        cache: true
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Format check
      run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze
      run: flutter analyze --fatal-infos --fatal-warnings
