// Mocks generated by Mockito 5.4.4 from annotations
// in re_view/test/features/player/core/pdf_cache_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:pdfx/src/renderer/interfaces/document.dart' as _i3;
import 'package:pdfx/src/renderer/interfaces/page.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePdfPage_0 extends _i1.SmartFake implements _i2.PdfPage {
  _FakePdfPage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePdfDocument_1 extends _i1.SmartFake implements _i3.PdfDocument {
  _FakePdfDocument_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePdfPageTexture_2 extends _i1.SmartFake
    implements _i2.PdfPageTexture {
  _FakePdfPageTexture_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PdfDocument].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfDocument extends _i1.Mock implements _i3.PdfDocument {
  MockPdfDocument() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get sourceName =>
      (super.noSuchMethod(
            Invocation.getter(#sourceName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#sourceName),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  int get pagesCount =>
      (super.noSuchMethod(Invocation.getter(#pagesCount), returnValue: 0)
          as int);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  set isClosed(bool? _isClosed) => super.noSuchMethod(
    Invocation.setter(#isClosed, _isClosed),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.PdfPage> getPage(
    int? pageNumber, {
    bool? autoCloseAndroid = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPage,
              [pageNumber],
              {#autoCloseAndroid: autoCloseAndroid},
            ),
            returnValue: _i5.Future<_i2.PdfPage>.value(
              _FakePdfPage_0(
                this,
                Invocation.method(
                  #getPage,
                  [pageNumber],
                  {#autoCloseAndroid: autoCloseAndroid},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.PdfPage>);
}

/// A class which mocks [PdfPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfPage extends _i1.Mock implements _i2.PdfPage {
  MockPdfPage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PdfDocument get document =>
      (super.noSuchMethod(
            Invocation.getter(#document),
            returnValue: _FakePdfDocument_1(this, Invocation.getter(#document)),
          )
          as _i3.PdfDocument);

  @override
  int get pageNumber =>
      (super.noSuchMethod(Invocation.getter(#pageNumber), returnValue: 0)
          as int);

  @override
  double get width =>
      (super.noSuchMethod(Invocation.getter(#width), returnValue: 0.0)
          as double);

  @override
  double get height =>
      (super.noSuchMethod(Invocation.getter(#height), returnValue: 0.0)
          as double);

  @override
  bool get autoCloseAndroid =>
      (super.noSuchMethod(
            Invocation.getter(#autoCloseAndroid),
            returnValue: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  set isClosed(bool? _isClosed) => super.noSuchMethod(
    Invocation.setter(#isClosed, _isClosed),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.PdfPageImage?> render({
    required double? width,
    required double? height,
    _i2.PdfPageImageFormat? format = _i2.PdfPageImageFormat.jpeg,
    String? backgroundColor,
    _i6.Rect? cropRect,
    int? quality = 100,
    bool? forPrint = false,
    bool? removeTempFile = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#render, [], {
              #width: width,
              #height: height,
              #format: format,
              #backgroundColor: backgroundColor,
              #cropRect: cropRect,
              #quality: quality,
              #forPrint: forPrint,
              #removeTempFile: removeTempFile,
            }),
            returnValue: _i5.Future<_i2.PdfPageImage?>.value(),
          )
          as _i5.Future<_i2.PdfPageImage?>);

  @override
  _i5.Future<_i2.PdfPageTexture> createTexture() =>
      (super.noSuchMethod(
            Invocation.method(#createTexture, []),
            returnValue: _i5.Future<_i2.PdfPageTexture>.value(
              _FakePdfPageTexture_2(
                this,
                Invocation.method(#createTexture, []),
              ),
            ),
          )
          as _i5.Future<_i2.PdfPageTexture>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PdfPageImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfPageImage extends _i1.Mock implements _i2.PdfPageImage {
  MockPdfPageImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get pageNumber =>
      (super.noSuchMethod(Invocation.getter(#pageNumber), returnValue: 0)
          as int);

  @override
  _i7.Uint8List get bytes =>
      (super.noSuchMethod(
            Invocation.getter(#bytes),
            returnValue: _i7.Uint8List(0),
          )
          as _i7.Uint8List);

  @override
  _i2.PdfPageImageFormat get format =>
      (super.noSuchMethod(
            Invocation.getter(#format),
            returnValue: _i2.PdfPageImageFormat.jpeg,
          )
          as _i2.PdfPageImageFormat);

  @override
  int get quality =>
      (super.noSuchMethod(Invocation.getter(#quality), returnValue: 0) as int);
}
